log:
  history_type: 'history-go-boilerplate'
  version: '1.0.0'

db:
  user: billing
  password: '1]tHj}X,gqn]w6'
  source_addrs:
    - 'dev-billing-mariadb-101.local.wavve.com:3306'
    - 'dev-billing-mariadb-102.local.wavve.com:3306'
  dbname: billing

redis:
  master_name: 'billing-kafka-sentinel'
  sentiel_addrs:
    - 'dev-billing-kafka-101.local.wavve.com:26379'
    - 'dev-billing-kafka-102.local.wavve.com:26379'
    - 'dev-billing-kafka-103.local.wavve.com:26379'

kafka:
  broker:
    - 'dev-kafka-product-01.local.wavve.com:9092'
    - 'dev-kafka-product-02.local.wavve.com:9092'
    - 'dev-kafka-product-03.local.wavve.com:9092'

sentry:
  dsn: ''
